DROP VIEW VW_PAGOS_EFECTUADOS;

CREATE VIEW VW_PAGOS_EFECTUADOS (
  IDPAGO,
  FECHA_PAGO,
  IMPORTE,
  TIPO_PAGO,
  NRO_CHEQUE,
  COBRADO,
  PROVEEDOR,
  COBRADOR
) AS

SELECT Pago.IDPAGO, Pago.FECHA_PAGO, Pago.IMPORTE, Pago.TIPO_PAGO, Pago.NRO_CHEQUE, Pago.COBRADO, Proveedor.RAZON_SOCIAL,
Personal.APELLIDO || ' ' || Personal.NOMBRE
FROM PAGO Pago
   INNER JOIN VW_IMPORTE_POR_IDPAGO_TOTAL Vw_importe_por_idpago_total
   ON  (Pago.IDPAGO = Vw_importe_por_idpago_total.IDPAGO)
   LEFT OUTER JOIN PERSONAL Personal
   ON  (Pago.IDPERSONAL = Personal.IDPERSONAL)
   INNER JOIN PROVEEDOR Proveedor
   ON  (Vw_importe_por_idpago_total.IDPROVEEDOR = Proveedor.IDPROVEEDOR)
;

