ALTER TABLE SERV_EDIF ADD A_PAGAR_OCUPANTE VARCHAR(2) DEFAULT 'No' NOT NULL;

ALTER TABLE SERV_EDIF ADD IDPERSONA INTEGER;

CREATE VIEW VW_DEUDORES
AS
SELECT Serv_edif.COSTO, Serv_edif.NRO_FACT, Serv_edif.IDPERSONA, Vw_personas_2.OCUPANTE, Vw_personas_2.TIPO, Vw_personas_2.MATRICULA, Serv_edif.fecha_pago, Servicio.DESCRIP
FROM SERV_EDIF Serv_edif
   LEFT OUTER JOIN VW_PERSONAS_2 Vw_personas_2
   ON  (Serv_edif.IDPERSONA = Vw_personas_2.IDOCUPANTE)
   INNER JOIN SERVICIO Servicio
   ON  (Serv_edif.IDSERVICIO = Servicio.IDSERVICIO)
WHERE  Serv_edif.A_PAGAR_OCUPANTE = 'Si'