INSERT INTO TIPO_PERSONAL(ID_TIPO_PERSONAL, DESCRIP) VALUES(1,'Superior');
INSERT INTO TIPO_PERSONAL(ID_TIPO_PERSONAL, DESCRIP) VALUES(2,'Subalterno');
INSERT INTO TIPO_PERSONAL(ID_TIPO_PERSONAL, DESCRIP) VALUES(3,'Civil');
INSERT INTO TIPO_PERSONAL(ID_TIPO_PERSONAL, DESCRIP) VALUES(4,'Remanentes');

INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(1,1);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(1,7);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(1,8);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(1,9);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(1,11);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(1,32);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(2,2);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(2,3);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(2,5);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(2,6);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(2,10);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(2,12);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(3,2);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(3,3);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(3,5);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(3,6);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(3,12);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,1);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,2);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,3);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,5);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,6);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,7);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,8);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,9);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,10);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,11);
INSERT INTO EDIFICIO_TIPO_PERSONAL(ID_TIPO_PERSONAL, IDEDIFICIO) VALUES(4,12);


