CREATE TABLE TIPO_LOCACION (
IDTIPO_LOCACION INTEGER NOT NULL,
DESCRIP VARCHAR(20),
PRIMARY KEY(IDTIPO_LOCACION));

INSERT INTO TIPO_LOCACION (IDTIPO_LOCACION, DESCRIP) VALUES(1, 'Departamento');
INSERT INTO TIPO_LOCACION (IDTIPO_LOCACION, DESCRIP) VALUES(2, 'Edificio');

ALTER TABLE COSTO_DEPTO_VACIO DROP TIPO_LOCACION;

ALTER TABLE COSTO_DEPTO_VACIO ADD IDTIPO_LOCACION INTEGER NOT NULL;

ALTER TABLE COSTO_DEPTO_VACIO ADD FOREIGN KEY(IDTIPO_LOCACION) REFERENCES TIPO_LOCACION(IDTIPO_LOCACION);

ALTER TABLE COSTO_DEPTO_VACIO ADD MONTO_EXP_EDIF FLOAT NOT NULL;

CREATE VIEW VW_CANT_ACTIVOS_X_EDIF (
IDEDIFICIO,
CANT_ACTIVOS) AS
SELECT EDIFICIO.IDEDIFICIO, COUNT( Departamento.IDDEPARTAMENTO ) CANT_ACTIVOS
FROM EDIFICIO
   LEFT OUTER JOIN DEPARTAMENTO Departamento
   ON  (EDIFICIO.IDEDIFICIO = Departamento.IDEDIFICIO AND DEPARTAMENTO.ACTIVO = 'SI')
GROUP BY EDIFICIO.IDEDIFICIO, EDIFICIO.IDOCUPANTEJEFE, EDIFICIO.DIRECCION, EDIFICIO.ADMFISCAL, EDIFICIO.OBSERVACIONES, EDIFICIO.DESCRIPCION, EDIFICIO.JEFEMILITAR, EDIFICIO.ECONOMO, EDIFICIO.COEFICIENTE
;

CREATE VIEW VW_EDIFICIOS (
IDEDIFICIO,
IDOCUPANTEJEFE,
DIRECCION,
ADMFISCAL,
OBSERVACIONES,
DESCRIPCION,
JEFEMILITAR,
ECONOMO,
COEFICIENTE,
CANT_DEPTOS) AS
SELECT EDIFICIO.IDEDIFICIO, EDIFICIO.IDOCUPANTEJEFE, EDIFICIO.DIRECCION, EDIFICIO.ADMFISCAL, EDIFICIO.OBSERVACIONES, EDIFICIO.DESCRIPCION, EDIFICIO.JEFEMILITAR, EDIFICIO.ECONOMO, EDIFICIO.COEFICIENTE, COUNT( Departamento.IDDEPARTAMENTO ) CANT_DEPTOS
FROM EDIFICIO
   LEFT OUTER JOIN DEPARTAMENTO Departamento
   ON  (EDIFICIO.IDEDIFICIO = Departamento.IDEDIFICIO)
GROUP BY EDIFICIO.IDEDIFICIO, EDIFICIO.IDOCUPANTEJEFE, EDIFICIO.DIRECCION, EDIFICIO.ADMFISCAL, EDIFICIO.OBSERVACIONES, EDIFICIO.DESCRIPCION, EDIFICIO.JEFEMILITAR, EDIFICIO.ECONOMO, EDIFICIO.COEFICIENTE
;

CREATE VIEW VW_CANT_OCUPADOS_X_EDIF (
IDEDIFICIO,
CANT_OCUPADOS) AS
SELECT EDIFICIO.IDEDIFICIO, COUNT( Departamento.IDDEPARTAMENTO ) CANT_OCUPADOS
FROM EDIFICIO
   INNER JOIN DEPARTAMENTO Departamento
   ON  (Departamento.IDEDIFICIO = EDIFICIO.IDEDIFICIO)
   INNER JOIN OCUPACION Ocupacion
   ON  (Ocupacion.IDDEPARTAMENTO = Departamento.IDDEPARTAMENTO AND OCUPACION.FECHARETIRO IS NULL)
GROUP BY EDIFICIO.IDEDIFICIO;

SET TERM ^ ;


/* Triggers only will work for SQL triggers */

CREATE TRIGGER AUTOENUMCOSTODEPTOVACIO FOR COSTO_DEPTO_VACIO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
 NEW.IdCOSTO_DEPTO_VACIO=GEN_ID(GEN_COSTODEPTOVACIO,1);
END
 ^

COMMIT WORK ^
SET TERM ;^