CREATE VIEW VW_RESUMEN_DECI_MANT
(EDIFICIO, FECHA, IMPORTE_EFEC, IMPORTE_RAE)
AS
SELECT EDIFICIO, FECHA, SUM(COSTO) IMPORTE_EFEC, CAST(0 AS FLOAT) AS IMPORTE_RAE FROM VW_CUENTA_MANT
WHERE TIPOPAGO = 'E'
GROUP BY EDIFICIO, FECHA

UNION

SELECT EDIFICIO, FECHA, CAST(0 AS FLOAT) AS IMPORTE_EFEC, SUM(COSTO) IMPORTE_RAE FROM VW_CUENTA_MANT
WHERE TIPOPAGO = 'R'
GROUP BY EDIFICIO, FECHA
;

CREATE VIEW VW_RESUMEN_DECI_SERV (
  EDIFICIO,
  FECHA,
  IMPORTE_EFEC,
  IMPORTE_CHEQUE
) AS

SELECT EDIFICIO, FECHA, SUM(COSTO) IMPORTE_EFEC, CAST(0 AS FLOAT) AS IMPORTE_CHEQUE FROM VW_SERV_EDIF
WHERE TIPO_PAGO = 'E'
GROUP BY EDIFICIO, FECHA
UNION
SELECT EDIFICIO, FECHA, CAST(0 AS FLOAT) AS IMPORTE_EFEC, SUM(COSTO) IMPORTE_CHEQUE FROM VW_SERV_EDIF
WHERE TIPO_PAGO = 'C'
GROUP BY EDIFICIO, FECHA;

