DROP TABLE DESCUENTO_MANUAL;

CREATE TABLE DESCUENTO_MANUAL
(
  IDDESCUENTO	INTEGER NOT NULL,
  IDOCUPANTE	INTEGER NOT NULL,
  IDTIPODESCUENTO	INTEGER NOT NULL,
  MES	VARCHAR(10),
  ANIO	INTEGER,
  MONTO	FLOAT,
  NRO_FACT	INTEGER,
CONSTRAINT DESC_MANUAL_PK PRIMARY KEY (IDDESCUENTO)
);
ALTER TABLE DESCUENTO_MANUAL ADD CONSTRAINT DESC_MANUAL_OCUPANTE_FK FOREIGN KEY (IDOCUPANTE) REFERENCES PERSONA (IDPERSONA) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE DESCUENTO_MANUAL ADD CONSTRAINT DESC_MANUAL_TIPODESCUENTO_FK FOREIGN KEY (IDTIPODESCUENTO) REFERENCES TIPO_DESCUENTO (IDTIPODESCUENTO) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE GENERATOR GR_DESCUENTO_MANUAL;

SET TERM ^ ;



/* Triggers only will work for SQL triggers */

CREATE TRIGGER AUTOENUMDESCMANUAL FOR DESCUENTO_MANUAL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
 NEW.IdDescuento=GEN_ID(GR_DESCUENTO_MANUAL,1);
END
 ^

COMMIT WORK ^
SET TERM ;^
