CREATE GENERATOR GEN_COSTODEPTOVACIO;

drop TABLE COSTO_DEPTO_VACIO;

CREATE TABLE COSTO_DEPTO_VACIO
(
  IDCOSTO_DEPTO_VACIO INTEGER NOT NULL,
  IDLOCACION INTEGER NOT NULL,
  TIPO_LOCACION VARCHAR(1),
  MES	VARCHAR(10),
  ANIO	INTEGER,
  MONTO_ADMIN	FLOAT,
  MONTO_EXP FLOAT,
CONSTRAINT COSTO_DEPTO_VACIO_PK PRIMARY KEY (IDCOSTO_DEPTO_VACIO)
);


SET TERM ^ ;
CREATE TRIGGER AUTOENUMCOSTODEPTOVACIO FOR COSTO_DEPTO_VACIO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
 NEW.IdCOSTO_DEPTO_VACIO=GEN_ID(GEN_COSTODEPTOVACIO,1);
END
 ^

COMMIT WORK ^
SET TERM ;^
