CREATE TABLE FECHA_DESCUENTO
(
  IDFECHA_DESCUENTO INTEGER NOT NULL,
  IDTIPO_DESCUENTO	INTEGER NOT NULL,
  FECHA DATE NOT NULL,
  MES	VARCHAR(10) NOT NULL,
  ANIO	INTEGER NOT NULL,
  MONTO	FLOAT NOT NULL,
  DEPTOS_ACTIVOS INTEGER NOT NULL,
CONSTRAINT FECHA_DESCUENTO_PK PRIMARY KEY (IDFECHA_DESCUENTO)
);

ALTER TABLE FECHA_DESCUENTO ADD FOREIGN KEY(IDTIPO_DESCUENTO) REFERENCES TIPO_DESCUENTO(IDTIPODESCUENTO);

INSERT INTO TIPO_DESCUENTO(CODDESC, OPERACION, TIPOPAGO, DESCRIPCION) VALUES (420, 'RESTA', '01', 'Expensas Deptos. Vacios');

UPDATE TIPO_DESCUENTO SET CODDESC = 420 WHERE IDTIPODESCUENTO = 3;

CREATE GENERATOR GEN_IDFECHA_DESCUENTO;

SET TERM ^ ;


/* Triggers only will work for SQL triggers */

CREATE TRIGGER AUTOENUMFECHADESCUENTO FOR FECHA_DESCUENTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
 NEW.IdFECHA_Descuento=GEN_ID(GEN_IDFECHA_DESCUENTO,1);
END
 ^

COMMIT WORK ^
SET TERM ;^