ALTER TABLE DEPARTAMENTO ADD TELEFONO VARCHAR(20);

ALTER TABLE OCUPANTE_MILITAR ADD TELEFONO_DESTINO VARCHAR(6);

ALTER TABLE OCUPANTE_CIVIL ADD TELEFONO_DESTINO VARCHAR(6);

CREATE TABLE TIPO_PERSONAL (
ID_TIPO_PERSONAL INT NOT NULL,
DESCRIP VARCHAR(15) NOT NULL,
PRIMARY KEY(ID_TIPO_PERSONAL),
UNIQUE(DESCRIP));

CREATE TABLE EDIFICIO_TIPO_PERSONAL (
ID_TIPO_PERSONAL INT NOT NULL,
IDEDIFICIO INT NOT NULL,
PRIMARY KEY(ID_TIPO_PERSONAL, IDEDIFICIO),
FOREIGN KEY(ID_TIPO_PERSONAL) REFERENCES TIPO_PERSONAL(ID_TIPO_PERSONAL),
FOREIGN KEY(IDEDIFICIO) REFERENCES EDIFICIO(IDEDIFICIO));

DROP VIEW VW_OCUPANTES_ACTUALES;

CREATE VIEW VW_OCUPANTES_ACTUALES (
  IDOCUPANTE,
  OCUPANTE,
  TIPO,
  LOCACION,
  FECHAINI,
  FECHAFIN,
  IDEDIFICIO,
  IDDEPARTAMENTO,
  MATRICULA,
  UNIDAD,
  TEL_UNIDAD,
  GRADO,
  DESTINO,
  TEL_DESTINO
) AS

SELECT Ocupacion.IDOCUPANTE, Persona.APELLIDO || ' ' || Persona.NOMBRE as OCUPANTE,
cast('Personal militar' as varchar(20)) as TIPO, Edificio.DESCRIPCION || ' ' || Departamento.DESCRIPCION AS LOCACION,
Ocupacion.FECHAINI, Ocupacion.FECHAFIN, Ocupacion.IDEDIFICIO,
Ocupacion.IDDEPARTAMENTO, cast(Ocupante_militar.MATRICULA as varchar(10)) as matricula, Departamento.DESCRIPCION, Departamento.TELEFONO,
CAST(Grado.ABREVIATURA AS VARCHAR(10)), Ocupante_militar.DESTINO, Ocupante_militar.TELEFONO_DESTINO
FROM OCUPACION Ocupacion
   INNER JOIN PERSONA Persona
   ON  (Ocupacion.IDOCUPANTE = Persona.IDPERSONA)
   INNER JOIN EDIFICIO Edificio
   ON  (Ocupacion.IDEDIFICIO = Edificio.IDEDIFICIO)
   INNER JOIN DEPARTAMENTO Departamento
   ON  (Ocupacion.IDDEPARTAMENTO = Departamento.IDDEPARTAMENTO)
   INNER JOIN OCUPANTE_MILITAR Ocupante_militar
   ON  (Persona.IDPERSONA = Ocupante_militar.IDPERSONA)
   INNER JOIN GRADO Grado
   ON  (Ocupante_militar.IDGRADO = Grado.IDGRADO)
WHERE FECHARETIRO IS NULL AND PERSONA.TIPO = 'OCUP_MIL'
UNION
SELECT Ocupacion.IDOCUPANTE, Persona.APELLIDO || ' ' || Persona.NOMBRE as OCUPANTE,
cast('Personal civil' as varchar(20)), Edificio.DESCRIPCION || ' ' || Departamento.DESCRIPCION AS LOCACION,
Ocupacion.FECHAINI, Ocupacion.FECHAFIN, Ocupacion.IDEDIFICIO,
Ocupacion.IDDEPARTAMENTO, Ocupante_civil.legajo, Departamento.DESCRIPCION, Departamento.TELEFONO,
OCUPANTE_CIVIL.CATEGORIA, OCUPANTE_CIVIL.DESTINO, OCUPANTE_CIVIL.TELEFONO_DESTINO
FROM OCUPACION Ocupacion
   INNER JOIN PERSONA Persona
   ON  (Ocupacion.IDOCUPANTE = Persona.IDPERSONA)
   INNER JOIN EDIFICIO Edificio
   ON  (Ocupacion.IDEDIFICIO = Edificio.IDEDIFICIO)
   INNER JOIN DEPARTAMENTO Departamento
   ON  (Ocupacion.IDDEPARTAMENTO = Departamento.IDDEPARTAMENTO)
   INNER JOIN OCUPANTE_CIVIL Ocupante_civil
   ON  (Persona.IDPERSONA = Ocupante_civil.IDPERSONA)
WHERE FECHARETIRO IS NULL AND PERSONA.TIPO = 'OCUP_CIV'
UNION
SELECT Ocupacion.IDOCUPANTE, Persona.APELLIDO || ' ' || Persona.NOMBRE as OCUPANTE,
cast('Particular' as varchar(20)), Edificio.DESCRIPCION || ' ' || Departamento.DESCRIPCION AS LOCACION,
Ocupacion.FECHAINI, Ocupacion.FECHAFIN, Ocupacion.IDEDIFICIO,
Ocupacion.IDDEPARTAMENTO, CAST('' AS VARCHAR(10)) AS MATRICULA, Departamento.DESCRIPCION, Departamento.TELEFONO,
CAST('' AS VARCHAR(10)) AS GRADO, CAST('' AS VARCHAR(30)) AS DESTINO, CAST('' AS VARCHAR(6)) AS TEL_DESTINO
FROM OCUPACION Ocupacion
   INNER JOIN PERSONA Persona
   ON  (Ocupacion.IDOCUPANTE = Persona.IDPERSONA)
   INNER JOIN EDIFICIO Edificio
   ON  (Ocupacion.IDEDIFICIO = Edificio.IDEDIFICIO)
   INNER JOIN DEPARTAMENTO Departamento
   ON  (Ocupacion.IDDEPARTAMENTO = Departamento.IDDEPARTAMENTO)
WHERE FECHARETIRO IS NULL AND PERSONA.TIPO = 'OCUP_PART'
;